# Generated by Django 5.1.7 on 2025-04-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('donation_type', models.CharField(max_length=100)),
                ('urgency', models.FloatField()),
                ('donor_name', models.CharField(max_length=200)),
                ('recipient_contact', models.CharField(max_length=200)),
                ('donor_contact', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('donation_type', models.CharField(max_length=100)),
                ('urgency', models.FloatField()),
                ('contact', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_contact', models.CharField(max_length=200)),
                ('donation_type', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=200)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.recipient')),
            ],
        ),
    ]
