# Generated by Django 5.2 on 2025-04-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='classified_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
    ]
